services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MONGODB_URI=${SPRING_MONGODB_URI}
      - STOCKFISH_PATH=/usr/games/stockfish

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend